### PR TITLE
React test

### PR DESCRIPTION
**Pull request by daorichard**
Added tests for app, signin, login react components

### CODE REVIEW

**Review by ericmrennie — APPROVED** [review]
Test 1,2 Test 1,2

**Review by CameronKirksey21 — APPROVED** [review]
Looks good! nice work Richard!

**Review by Ericesposito — APPROVED** [review]
Great work here, excited to run the tests.

**Comment by JasonY000** [comment]
good work!

**Review by JasonY000 — APPROVED** [review]
good work

**Pull request merged**
