### PR TITLE
update read me

### PR DESCRIPTION
**Pull request by JasonY000**
add in contribution.

### CODE REVIEW

**Review by daorichard — APPROVED** [review]
great job on the readme

**Review by ericmrennie — APPROVED** [review]
Great readme

**Review by Ericesposito — APPROVED** [review]
Readme is looking great, nice work Jason and Richard

**Review by CameronKirksey21 — APPROVED** [review]
Very informative

**Comment by JasonY000** [comment]
take a look at these changes.

**Pull request merged**
