### PR TITLE
Cameron

### PR DESCRIPTION
**Pull request by CameronKirksey21**
Navbar is done!

### CODE REVIEW

**Review by JasonY000 — COMMENTED** [review]
looks good to me!

**Comment by daorichard** [comment]
thats a very nice nav bar, very interactive, much wow

**Review by ericmrennie — APPROVED** [review]
Great nav bar!

**Review by JasonY000 — COMMENTED** [review]
looks good to me.

**Review by daorichard — APPROVED** [review]
approved

**Review by Ericesposito — APPROVED** [review]
Great work Cameron, this looks clean

**Pull request merged**
